providers:
  openai:
    api_keys:
      - key: "sk-proj-example1..."
        name: "primary"
        rate_limit: 1000  # requests per hour
        cost_limit: 100.0 # dollars per day
        enabled: true
      - key: "sk-proj-example2..."
        name: "secondary"
        rate_limit: 800
        cost_limit: 75.0
        enabled: true
      - key: "sk-proj-example3..."
        name: "backup"
        rate_limit: 500
        cost_limit: 50.0
        enabled: false  # disabled key
        
    models:  # Available models with their configurations
      - name: "gpt-4"
        input_cost_per_1k_tokens: 0.03
        output_cost_per_1k_tokens: 0.06
        max_tokens: 8192
        enabled: true
      - name: "gpt-3.5-turbo"
        input_cost_per_1k_tokens: 0.001
        output_cost_per_1k_tokens: 0.002
        max_tokens: 4096
        enabled: true
    
    # Key rotation strategy
    rotation:
      strategy: "round_robin"  # round_robin, least_used, cost_optimized, random
      interval: "1h"           # rotation interval
      health_check: true       # check key health before use
      fallback_enabled: true   # fallback to next key on failure

  anthropic:
    api_keys:
      - key: "sk-ant-example1..."
        name: "primary"
        rate_limit: 500
        cost_limit: 80.0
        enabled: true
      - key: "sk-ant-example2..."
        name: "secondary"
        rate_limit: 400
        cost_limit: 60.0
        enabled: true
    
    models:
      - name: "claude-3-sonnet-20240229"
        input_cost_per_1k_tokens: 0.003
        output_cost_per_1k_tokens: 0.015
        max_tokens: 4096
        enabled: true
      - name: "claude-3-haiku-20240307"
        input_cost_per_1k_tokens: 0.00025
        output_cost_per_1k_tokens: 0.00125
        max_tokens: 4096
        enabled: true
    
    rotation:
      strategy: "least_used"
      interval: "30m"
      health_check: true
      fallback_enabled: true

  gemini:
    api_keys:
      - key: "AIza-example1..."
        name: "primary"
        rate_limit: 600
        cost_limit: 70.0
        enabled: true
    
    models:
      - name: "gemini-pro"
        input_cost_per_1k_tokens: 0.0005
        output_cost_per_1k_tokens: 0.0015
        max_tokens: 2048
        enabled: true
    
    rotation:
      strategy: "single"  # only one key, no rotation
      health_check: false
      fallback_enabled: false

# Global settings
global:
  # Default fallback chain when primary provider fails
  fallback_chain: ["openai", "anthropic", "gemini"]
  
  # Global rate limiting
  global_rate_limit: 2000  # requests per hour across all providers
  
  # Cost monitoring
  daily_cost_limit: 500.0  # dollars per day across all providers
  cost_alert_threshold: 0.8  # alert when 80% of limit reached
  
  # Security settings
  encrypt_keys: true
  key_validation: true
  audit_logging: true
  
  # Rotation settings
  default_rotation_strategy: "round_robin"
  health_check_interval: "5m"
  key_timeout: "30s"